Repository st235/aura, pull requests merged in 2018-11, with the labels that each got.

#1 implemented items list.
  src/js/components/presentational/List.js
  src/styles/components/list.scss
  src/styles/index.scss
Labels: feature

#4 implemented text element.
  src/js/components/presentational/Text.js
Labels: feature

#3 Implement component for code presentation
  package.json
  src/js/components/presentional/Code.js
  src/styles/components/highlighter.scss
  src/styles/index.scss
Labels: enhancement

#5 add: containers
  src/js/components/container/CodeContainer.js
  src/js/components/container/DescriptionContainer.js
  src/js/components/container/ItemsContainer.js
  src/js/components/presentational/Code.js
  src/styles/components/headers.scss
Labels: enhancement

#7 implemented custom programming language.
  dist/app.js
  src/js/components/container/CodeContainer.js
  src/js/data/data.json
Labels: feature

#8 implemented base style fixes.
  dist/app.js
  src/styles/components/list.scss
  src/styles/index.scss
Labels: feature

#10 fixed columns count.
  dist/app.js
  src/js/components/container/AuraAppContainer.js
  src/js/components/container/CodeContainer.js
  src/js/components/container/ItemsContainer.js
  src/js/components/presentational/Code.js
Labels: bug

#11 implemented roboto font.
  dist/app.js
  dist/index.html
  src/html/index.html
  src/styles/components/highlighter.scss
  src/styles/index.scss
Labels: feature

#14 fix: apply border radius for selected item
  src/styles/components/list.scss
Labels: bug
